[phases.setup]
nixPkgs = ["nodePackages.pnpm"]

[phases.install]
cmds = ["cd world-game-app && pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["cd world-game-app && pnpm --filter @repo/api run build"]

[start]
cmd = "cd world-game-app && pnpm --filter @repo/api run start"
